name: Build WordPress Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build Plugin Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Install Node.js dependencies and build assets
        run: |
          npm ci
          npm run format

      - name: Create plugin directory
        run: |
          mkdir -p ./build/wp-link-analyzer

      - name: Copy plugin files
        run: |
          echo "Copying plugin files..."

          # Copy main plugin file (renamed from plugin.php to wp-link-analyzer.php)
          cp index.php ./build/wp-link-analyzer
          cp plugin.php ./build/wp-link-analyzer
          cp README.md ./build/wp-link-analyzer
          cp -r src ./build/wp-link-analyzer

      - name: Create zip archive
        run: |
          cd ./build
          zip -r wp-link-analyzer.zip wp-link-analyzer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-link-analyzer
          path: ./build/wp-link-analyzer.zip
          retention-days: 90

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/wp-link-analyzer.zip
          draft: false
          prerelease: false

      - name: Upload to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: wp-link-analyzer-latest
          path: ./build/wp-link-analyzer.zip
          retention-days: 90
          if-no-files-found: error
