name: PHP CodeSniffer lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']

    name: Lint with PHPCS. PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP and install dependencies
      uses: ./.github/actions/php-setup
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Lint with phpcs
      run: composer phpcs

