name: PHP Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']

    name: Run Unit Tests. PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: Run unit tests
      run: composer test-unit
